/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CashRouteImport } from './routes/cash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminNoveltiesRouteImport } from './routes/admin.novelties'
import { Route as AdminDailyMovementsRouteImport } from './routes/admin.daily-movements'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoveltiesRoute = AdminNoveltiesRouteImport.update({
  id: '/admin/novelties',
  path: '/admin/novelties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDailyMovementsRoute = AdminDailyMovementsRouteImport.update({
  id: '/admin/daily-movements',
  path: '/admin/daily-movements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/admin/daily-movements': typeof AdminDailyMovementsRoute
  '/admin/novelties': typeof AdminNoveltiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/receipt/$id': typeof ReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/admin/daily-movements': typeof AdminDailyMovementsRoute
  '/admin/novelties': typeof AdminNoveltiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/receipt/$id': typeof ReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/admin/daily-movements': typeof AdminDailyMovementsRoute
  '/admin/novelties': typeof AdminNoveltiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/receipt/$id': typeof ReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cash'
    | '/chat'
    | '/clients'
    | '/dashboard'
    | '/loans'
    | '/login'
    | '/reports'
    | '/admin/daily-movements'
    | '/admin/novelties'
    | '/admin/users'
    | '/clients/$id'
    | '/clients/new'
    | '/receipt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cash'
    | '/chat'
    | '/clients'
    | '/dashboard'
    | '/loans'
    | '/login'
    | '/reports'
    | '/admin/daily-movements'
    | '/admin/novelties'
    | '/admin/users'
    | '/clients/$id'
    | '/clients/new'
    | '/receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/cash'
    | '/chat'
    | '/clients'
    | '/dashboard'
    | '/loans'
    | '/login'
    | '/reports'
    | '/admin/daily-movements'
    | '/admin/novelties'
    | '/admin/users'
    | '/clients/$id'
    | '/clients/new'
    | '/receipt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashRoute: typeof CashRoute
  ChatRoute: typeof ChatRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  AdminDailyMovementsRoute: typeof AdminDailyMovementsRoute
  AdminNoveltiesRoute: typeof AdminNoveltiesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/novelties': {
      id: '/admin/novelties'
      path: '/admin/novelties'
      fullPath: '/admin/novelties'
      preLoaderRoute: typeof AdminNoveltiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/daily-movements': {
      id: '/admin/daily-movements'
      path: '/admin/daily-movements'
      fullPath: '/admin/daily-movements'
      preLoaderRoute: typeof AdminDailyMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
  ClientsNewRoute: ClientsNewRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashRoute: CashRoute,
  ChatRoute: ChatRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  AdminDailyMovementsRoute: AdminDailyMovementsRoute,
  AdminNoveltiesRoute: AdminNoveltiesRoute,
  AdminUsersRoute: AdminUsersRoute,
  ReceiptIdRoute: ReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
